export const LEGACY_MODEL_TOKENS = {
  announcement: Symbol('LEGACY_ANNOUNCEMENT_REPOSITORY'),
  assignment: Symbol('LEGACY_ASSIGNMENT_REPOSITORY'),
  attendance: Symbol('LEGACY_ATTENDANCE_REPOSITORY'),
  class: Symbol('LEGACY_CLASS_REPOSITORY'),
  classStudent: Symbol('LEGACY_CLASS_STUDENT_REPOSITORY'),
  comment: Symbol('LEGACY_COMMENT_REPOSITORY'),
  conversation: Symbol('LEGACY_CONVERSATION_REPOSITORY'),
  course: Symbol('COURSE_REPOSITORY'),
  document: Symbol('LEGACY_DOCUMENT_REPOSITORY'),
  material: Symbol('LEGACY_MATERIAL_REPOSITORY'),
  message: Symbol('LEGACY_MESSAGE_REPOSITORY'),
  onlineTest: Symbol('LEGACY_ONLINE_TEST_REPOSITORY'),
  post: Symbol('LEGACY_POST_REPOSITORY'),
  recordLessonSummary: Symbol('LEGACY_RECORD_LESSON_SUMMARY_REPOSITORY'),
  room: Symbol('LEGACY_ROOM_REPOSITORY'),
  semester: Symbol('LEGACY_SEMESTER_REPOSITORY'),
  submission: Symbol('LEGACY_SUBMISSION_REPOSITORY'),
  teachingSchedule: Symbol('LEGACY_TEACHING_SCHEDULE_REPOSITORY'),
  testAttempt: Symbol('LEGACY_TEST_ATTEMPT_REPOSITORY'),
  testQuestion: Symbol('LEGACY_TEST_QUESTION_REPOSITORY'),
  testSession: Symbol('LEGACY_TEST_SESSION_REPOSITORY'),
  topic: Symbol('LEGACY_TOPIC_REPOSITORY'),
  user: Symbol('USER_REPOSITORY'),
} as const;

export type LegacyModelName = keyof typeof LEGACY_MODEL_TOKENS;
