export const COLLABORATION_MODEL_TOKENS = {
  conversation: Symbol('COLLABORATION_CONVERSATION_REPOSITORY'),
  message: Symbol('COLLABORATION_MESSAGE_REPOSITORY'),
  recording: Symbol('COLLABORATION_RECORDING_REPOSITORY'),
  room: Symbol('COLLABORATION_ROOM_REPOSITORY'),
} as const;
